### ISSUE TITLE
Add rule(s) to check the usage of the Web App Manifest file

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#32]
- [x] Check if the manifest is specified and exists (done in #54)
- [x] Check if the manifest file is valid (partially done in: #56)
- [x] Check if the file is not sent with the `application/manifest+json` media type (will be solved by #141)
- [x] Check if the file extension is `webmanifest` (done in #39)

----

See: https://www.w3.org/TR/appmanifest/

**Comment by alrra** [comment]
* [Firefox for Android plans](https://www.youtube.com/watch?v=_sLa0qhuqcA&t=12m40s)

**Comment by alrra** [comment]
Firefox for Android:

* https://hacks.mozilla.org/2017/10/progressive-web-apps-firefox-android/
* https://www.youtube.com/watch?v=_sLa0qhuqcA&t=12m40s

**Comment by alrra** [comment]
For Samsung Internet, see: http://developer.samsung.com/internet/android/web-guide.
